well-typed/generics-sop

src/Generics/SOP/Sing.hs
I found that I had to recurse with both `Sing a` and `Shape a`. This allows one to only use `Shape a`.
=> SingI x to the context of Shape

.gitignore, generics-sop.cabal, src/Generics/SOP/TH.hs, test/Example.hs
Later part is useful if one doesn't want to introduce orphan `Generic` and `DatatypeInfo` instances, but wants to use sop framework to define instances of own class.
=> Fix deriveGenericOnly and add non-instance template derivation functions

src/Generics/SOP/Universe.hs
GHC now checks that default signatures differ from their method only in
their contexts.
=> Fix default signatures for GHC 8.2

src/Generics/SOP/BasicFunctors.hs
These instances may come in handy--particularly Applicative due to uses of hsequence--and they add no dependencies or even any additional imports.
=> Added Applicative, Foldable and Traversable instances for (:.:)

doctest.sh, src/Generics/SOP/Classes.hs, src/Generics/SOP/NS.hs
Resolves https://github.com/well-typed/generics-sop/issues/28
I didn't add `hapInjs'`, it's signature is
```haskell
class (UnProd (Prod h) ~ h) => HApInjs' (h :: (k -> *) -> (l -> *)) where
hapInjs' :: (SListIN h xs) => Prod h f xs -> NP (K (h f xs)) xs
```
but we don't yet know about `NP` in `Classes.hs`
*EDIT* doctests don't pass, as derived `Show` adds parentheses (i.e. doesn't take fixity into account); we can change `Show` or leave it alone; `doctest.sh` is still useful to give quick overview
=> apInjs'_POP and apInjs'_NP

generics-sop.cabal, src/Generics/SOP.hs, src/Generics/SOP/Classes.hs, src/Generics/SOP/Constraint.hs, src/Generics/SOP/NP.hs, src/Generics/SOP/NS.hs, test/Example.hs, test/HTransExample.hs
This introduces one of the most frequently requested features.
All the current functions operating on NPs, NSs, SOPs, POPs, leave what I call the "signature" of the structure unchanged. The "signature" being the type-level list (of lists) describing the contents of the structure. Only the "interpretation" (i.e., the type constructor) can be changed.
This, however, breaks down if we want to convert between truly different datatypes, or exploit that a datatype's components adhere to a particular property. An example would be that a datatype has fields that are all wrapped in a Maybe application, and you'd like to turn it into an `SOP Maybe ...` rather than an `SOP I ...`.
For this conversion, `fromI_SOP` and `toI_SOP` are now offered. The `coerce_*` and `trans_*` functions offer more …
=> AllZip and trans_*

src/Generics/SOP.hs, src/Generics/SOP/NS.hs
These are another two useful functions. They can be used to implement things like generic equality and ordering, among others.
I think this pattern occurs often enough that it deserves its own function. I also want to avoid as much as possible that end users have to write functions that traverse the (linear) structure of sums and products manually. For example, I'm playing with a different internal representation in the compact-representation branch that would make this sort of stuff less efficient, but would still allow an efficient direct implementation of `ccompare_NS`.
Documentation still to be added.
Also no idea if SOP version and `hcompare` should be added.
This is how `ccompare_SOP` would probably look like:
```
ccompare_SOP ::
forall c proxy r f g xss .
(All2 c xss)
=> proxy c
-> …
```
=> Add compare_NS and ccompare_NS.

src/Generics/SOP/GGP.hs, src/Generics/SOP/Instances.hs, src/Generics/SOP/NS.hs, src/Generics/SOP/TH.hs
Despite having lots of fancy types at its disposal, `generics-sop` bails out to `error` clauses in several places, which feels silly. This removes as many `error` cases as possible using the `EmptyCase` extension, which has the benefit of making several functions actually total.
This is a bit of a breaking change in that the TH-generated code now requires the `EmptyCase` extension. If this is a step too far, I could revert that part and only submit the remaining patch (since the rest of it does not constitute a breaking change by itself).
Fixes #57.
=> Remove most uses of 'error' using EmptyCase

generics-sop/generics-sop.cabal, generics-sop/src/Generics/SOP/GGP.hs, generics-sop/src/Generics/SOP/Metadata.hs, generics-sop/src/Generics/SOP/Type/Metadata.hs, generics-sop/src/Generics/SOP/Universe.hs, sop-core/sop-core.cabal, sop-core/src/Data/SOP/BasicFunctors.hs, sop-core/src/Data/SOP/Classes.hs, sop-core/src/Data/SOP/Constraint.hs, sop-core/src/Data/SOP/NP.hs, sop-core/src/Data/SOP/NS.hs, sop-core/src/Data/SOP/Sing.hs
Supersedes #67.
Enabling `NoStarIsType` bans from accidental use of `*` as `Type`.
=> Use Type instead of *

generics-sop/src/Generics/SOP.hs, generics-sop/src/Generics/SOP/Metadata.hs, generics-sop/src/Generics/SOP/Type/Metadata.hs, generics-sop/src/Generics/SOP/Universe.hs, sop-core/src/Data/SOP.hs, sop-core/src/Data/SOP/Constraint.hs, sop-core/src/Data/SOP/Dict.hs, sop-core/src/Data/SOP/NP.hs, sop-core/src/Data/SOP/NS.hs, sop-core/src/Data/SOP/Sing.hs
This fixes #32.
It remains to be decided whether this should go into 0.4 or a later release, because it is a rather invasive change. I believe the external interface will behave mostly the same though.
=> Refactor SListI to be a special case of All

.travis.yml, generics-sop/generics-sop.cabal, sop-core/sop-core.cabal
This also fixes `doctest` running (as `cabal` doesn't by default generate env files)
=> Regenerate .travis.yml

generics-sop/src/Generics/SOP/GGP.hs, generics-sop/src/Generics/SOP/Metadata.hs, generics-sop/src/Generics/SOP/TH.hs, generics-sop/src/Generics/SOP/Type/Metadata.hs
This is one option to solve #76.
We add a POP with strictness information to the metadata
for datatypes, but not newtypes.
Both GGP and TH generation are adapted to produce this
information.
=> Add strictness info to metadata.

sop-core/src/Data/SOP/Sing.hs
GHC 8.10 (HEAD) implements GHC [proposal 24](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0024-no-kind-vars.rst), which requires kind variables to be quantified alongside type variables in a top-level `forall`. Currently, the kind variables in the top-level `forall`s of the `shape` and `lengthSList` functions are not explicitly quantified, which means that `sop-core` fails to build on GHC HEAD.
Luckily, the fix is backwards compatible, since the earliest version of GHC that `sop-core` supports now is GHC 8.0, which includes the ability to explicitly quantify kind variables. Note that this ability required the use of the `TypeInType` extension prior to GHC 8.6, which is why I selectively enable it on old GHCs, but after 8.6 it only requires `PolyKinds`.
Patch …
=> Explicitly quantify the kind variable in `shape` and `lengthSList`

sop-core/src/Data/SOP/Classes.hs
`HTrans h1 h2` is implied by the parent class.
=> Drop redundant HTrans constraint in hcoerce's context

generics-sop/generics-sop.cabal, generics-sop/src/Generics/SOP/TH.hs, generics-sop/test/Example.hs
This leverages the `th-abstraction` library to grant `Generics.SOP.TH` the ability to generate code for vanilla data types and data families alike. This patch looks large, but most of it is internal refactoring to use `th-abstraction`'s intermediate data types where necessary (e.g., `DatatypeInfo` instead of `Dec`, `ConstructorInfo` instead of `Con`, etc.).
This does incur an extra library dependency in `th-abstraction`, but it's a very small one, as it does not depend on any non-GHC-boot libraries itself. It's also used by other libraries to enable data family support, such as `aeson` and `th-lift`.
Fixes #111 along the way.
=> RFC: TH support for data families

sop-core/src/Data/SOP/Dict.hs
GHC HEAD now implements [proposal 229](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst), which makes the parser more sensitive to whitespace around `@` characters in as-patterns. In particular, `@`s in as-patterns are no longer permitted to have preceding or trailing whitespace, which causes `sop-core` to fail to compile on HEAD:
```
[7 of 8] Compiling Data.SOP.Dict    ( src/Data/SOP/Dict.hs, interpreted )
src/Data/SOP/Dict.hs:71:1: error: Parse error in pattern: mapAll2
|
71 | mapAll2 f d @ Dict = (all2 . mapAll (mapAll f) . unAll2) d
| ^^^^^^^^^^^
```
The fix is simple: remove the extra whitespace, which this patch accomplishes.
=> Make sop-core forward-compatible with GHC proposal 229

generics-sop/CHANGELOG.md, generics-sop/generics-sop.cabal, generics-sop/src/Generics/SOP/Instances.hs, generics-sop/src/Generics/SOP/TH.hs, sop-core/sop-core.cabal
benchmarks fail on CI, but this should soon be resolved when `aeson` supports `th-abstraction-0.4`
=> Use th-abstraction-0.4, support GHC-9.0

generics-sop/generics-sop.cabal, generics-sop/src/Generics/SOP/Instances.hs, sop-core/sop-core.cabal
Fixes #145
﻿Using `__GLASGOW_HASKELL__` because there doesn't seem to be any sort of MAX_VERSION_base
=> Support ghc 9.2

sop-core/src/Data/SOP/NP.hs, sop-core/src/Data/SOP/NS.hs
Hello there. I've been making good use of the handy `[c]ana_N{S,P}` functions for constructing things coinductively.
Unfortunately I've run into a bit of a hiccup: the continuations expected by these functions are not granted `SListI` constraints on their list-kinded type variables. Since it's not possible to case analyze naked type variables in Haskell (even when their kind is a promoted inductive type), this restricts you from doing much of use, unless you explicitly pass dictionaries into your `s`.
I believe the correct thing to do here is to pass down the sub-constraint-dictionary revealed by pattern matching into the continuation.
=> Expose SListI in coalgebras

sop-core/src/Data/SOP/NS.hs
Found by @phadej.
This is an interface-incompatible change. On the other hand, I doubt anybody has been using these functions at their clearly incorrect types.
Note that furthermore, `ctraverse_NS` is an example of several functions in the library which currently have an unnecessary `Applicative` constraint where a `Functor` constraint would suffice.
=> Fix types of ctraverse_NS and ctraverse_SOP.

generics-sop/generics-sop.cabal, generics-sop/src/Generics/SOP/Instances.hs, generics-sop/src/Generics/SOP/TH.hs, sop-core/sop-core.cabal
Resolves #172 
Note that the [code changes in TH.hs](https://github.com/well-typed/generics-sop/pull/173/files#diff-84fb050a33526c3b1405760704355071e219b5cb3b906f9437df03d829b54c0b) were made by applying suggestions from the [th-abstraction migration guide](https://hackage.haskell.org/package/th-abstraction-0.6.0.0/changelog) until it type-checked, I had no real understanding of what I was doing. The tests do pass for me locally.
=> Support GHC 9.8.1
